### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by Vladnev** [lordthorzonus/yii2-monolog#4]
Hi you maybe missed to register package:

> The requested package leinonen/yii2-monolog could not be found in any version, there may be a typo in the package name.

And create please release - to make possibility mark it in composer.json

**Comment by lordthorzonus** [comment]
Hi! This is because I haven't made a stable release yet. I think I'll finish 1.0 during the December holidays. There is still going to be some breaking changes for configuring the log targets and using the actual component (currently undocumented). 

Releasing of this package was postponed because of some shifts in priority with the company I work in :). Sorry for the confusion.

**Comment by lordthorzonus** [comment]
I'll leave this issue open and ping here when the release is done :+1:

**Comment by Vladnev** [comment]
Cool, thnx.
I think this package best solution for integrate in working app 👍
Let me know - If you need some help, I'll be glad.

**Comment by danielbehrendt** [comment]
Hi, are there any news/plans for the first stable release? I'm also looking foward to use this extension.

**Comment by lordthorzonus** [comment]
@bitmatix  @Vladnev  Yep I think I have finalized the config api now and the component is fully working + covered with tests.. The docs need a bit of reread and probably couple of informative exceptions should be added but I think I can do the release this week :)

**Comment by danielbehrendt** [comment]
@lordthorzonus sounds great 👍 any updates on this?

**Comment by danielbehrendt** [comment]
@lordthorzonus any updates?

**Comment by lordthorzonus** [comment]
@bitmatix  @Vladnev Hi guys! Sorry for taking so long.. Just tagged the 1.0.0 release and will follow semver after this :). https://packagist.org/packages/leinonen/yii2-monolog

Please ping me if there are any problems or the API is unintuitive etc. 

And sorry again for the delay.
